/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElText: typeof import('element-plus/es')['ElText']
    ElTypographyText: typeof import('element-plus/es')['ElTypographyText']
    EsEditor: typeof import('./src/components/es-editor/es-editor.vue')['default']
    EsModalForm: typeof import('./src/components/es-modal-form/index.vue')['default']
    EsUpload: typeof import('./src/components/es-upload/es-upload.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
