/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATypographyText: typeof import('ant-design-vue/es')['TypographyText']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    EsCheckbox: typeof import('./src/components/es-checkbox-group/es-checkbox.vuee')['default']
    EsCheckboxGroup: typeof import('./src/components/es-checkbox-group/es-checkbox-group.vue')['default']
    EsEditor: typeof import('./src/components/es-editor/es-editor.vue')['default']
    EsModalForm: typeof import('./src/components/es-modal-form/index.vue')['default']
    EsTable: typeof import('./src/components/es-table/index.vue')['default']
    EsUpload: typeof import('./src/components/es-upload/es-upload.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
